"""End-to-end PGP test.

Generates a real (small) PGP keypair locally for the "user" and another
one for the "inbox", exercises the full create-inbox → send → decrypt
loop, then the reverse flow (user encrypts an incoming reply; agent
decrypts on read).

The inbox keypair is also generated by PGPy directly at 2048 bits and
fed in via monkeypatch on `nobox.pgp.generate_inbox_keypair` so the test
doesn't pay the cost of nobox's default 4096-bit RSA keygen on every
run (still slow enough to be honest about — see the module-scoped
fixture; keygen happens once per pytest session).
"""

from __future__ import annotations

import re

import httpx
import pytest
import respx

pgpy = pytest.importorskip("pgpy")

from nobox import inbox as inbox_mod  # noqa: E402
from nobox import pgp as nobox_pgp  # noqa: E402
from nobox import service, state  # noqa: E402
from nobox.github_client import GitHubClient  # noqa: E402
from nobox.state import MessageRow  # noqa: E402

PGP_BLOCK_RE = re.compile(
    r"-----BEGIN PGP MESSAGE-----.+?-----END PGP MESSAGE-----",
    re.DOTALL,
)


def _gen_test_key(uid: str, bits: int = 2048) -> pgpy.PGPKey:
    """Generate a real PGPy keypair small enough to be fast in tests."""
    key = pgpy.PGPKey.new(pgpy.constants.PubKeyAlgorithm.RSAEncryptOrSign, bits)
    uid_obj = pgpy.PGPUID.new(uid)
    key.add_uid(
        uid_obj,
        usage={
            pgpy.constants.KeyFlags.Sign,
            pgpy.constants.KeyFlags.EncryptCommunications,
            pgpy.constants.KeyFlags.EncryptStorage,
        },
        hashes=[pgpy.constants.HashAlgorithm.SHA256],
        ciphers=[pgpy.constants.SymmetricKeyAlgorithm.AES128],
        compression=[pgpy.constants.CompressionAlgorithm.Uncompressed],
    )
    return key


# Module-scoped: keygen takes ~1-3s each, so we generate once and reuse.
@pytest.fixture(scope="module")
def user_key() -> pgpy.PGPKey:
    return _gen_test_key("Test User <user@nobox.local>")


@pytest.fixture(scope="module")
def inbox_key() -> pgpy.PGPKey:
    return _gen_test_key("nobox-pgp-test <noreply@nobox.local>")


@pytest.fixture
def pgp_inbox(tmp_path, monkeypatch, user_key, inbox_key):
    """Create a PGP-enabled inbox with mocked GitHub I/O and inbox keygen.

    Returns the InboxRow. State (per-inbox dir + SQLite row) is populated
    so downstream tests can run send_message and read_message against it.
    """
    # The user's pubkey lives at this path; nobox will read it during create.
    user_pub_path = tmp_path / "user.pub.asc"
    user_pub_path.write_text(str(user_key.pubkey))

    # Skip the expensive 4096-bit RSA keygen in nobox by feeding our 2048-bit
    # key in through the public helper's seam.
    def _fake_keygen(*, uid):
        return nobox_pgp.Keypair(
            priv_armored=str(inbox_key),
            pub_armored=str(inbox_key.pubkey),
            fingerprint=str(inbox_key.fingerprint).replace(" ", ""),
        )

    monkeypatch.setattr(nobox_pgp, "generate_inbox_keypair", _fake_keygen)

    with respx.mock(base_url="https://api.github.com") as router:
        router.get("/user").mock(
            return_value=httpx.Response(200, json={"login": "evilsocket"})
        )
        router.get("/repos/evilsocket/test").mock(
            return_value=httpx.Response(200, json={"has_issues": True})
        )
        router.post("/repos/evilsocket/test/issues").mock(
            return_value=httpx.Response(
                201,
                json={"number": 1, "id": 100, "node_id": "I_abc"},
            )
        )
        with GitHubClient("tok") as c:
            row = inbox_mod.create_inbox(
                c,
                name="pgptest",
                repo="evilsocket/test",
                pgp_enabled=True,
                user_pgp_key_path=user_pub_path,
                pop_mode=False,
            )
    return row


# ---------- create-inbox ---------------------------------------------------


def test_pgp_inbox_lays_down_all_three_key_files(pgp_inbox):
    d = state.inbox_dir(pgp_inbox.name)
    assert (d / "pgp.priv.asc").exists()
    assert (d / "pgp.pub.asc").exists()
    assert (d / "user.pub.asc").exists()
    assert pgp_inbox.pgp_enabled is True
    # Sanity: the files are real armored keys.
    assert "BEGIN PGP PRIVATE KEY BLOCK" in (d / "pgp.priv.asc").read_text()
    assert "BEGIN PGP PUBLIC KEY BLOCK" in (d / "pgp.pub.asc").read_text()
    assert "BEGIN PGP PUBLIC KEY BLOCK" in (d / "user.pub.asc").read_text()


# ---------- send: agent → user ---------------------------------------------


def test_send_message_encrypts_so_only_user_can_decrypt(pgp_inbox, monkeypatch, user_key):
    """The posted comment body must be PGP ciphertext decryptable by the user."""
    posted = {}

    def _capture_post(self, owner, repo, number, body):
        posted["body"] = body
        return {
            "id": 901,
            "created_at": "2026-05-21T15:00:00Z",
            "updated_at": "2026-05-21T15:00:00Z",
        }

    monkeypatch.setattr(
        "nobox.github_client.GitHubClient.post_issue_comment", _capture_post
    )

    plaintext = "Hello agent. This is secret."
    service.send_message(pgp_inbox, plaintext)

    body = posted["body"]
    # The plaintext must NOT be present in the posted body.
    assert plaintext not in body
    # There must be a PGP MESSAGE block.
    block_match = PGP_BLOCK_RE.search(body)
    assert block_match, f"no PGP message block found in posted body: {body!r}"

    # The user's private key recovers the plaintext.
    encrypted = pgpy.PGPMessage.from_blob(block_match.group(0))
    decrypted = user_key.decrypt(encrypted)
    assert str(decrypted.message).strip() == plaintext


# ---------- read: user → agent ---------------------------------------------


def test_read_message_decrypts_incoming_user_reply(
    pgp_inbox, monkeypatch, inbox_key, user_key
):
    """A user reply encrypted to the inbox pubkey is auto-decrypted on read."""
    plaintext = "Incoming encrypted reply -- ack the previous task."

    # User builds a PGP message → signs with their own privkey → encrypts to
    # the inbox's pubkey. Same shape as a real email reply with GPG.
    msg = pgpy.PGPMessage.new(plaintext)
    msg |= user_key.sign(msg)
    encrypted = inbox_key.pubkey.encrypt(msg)
    comment_body = f"```text\n{str(encrypted).strip()}\n```\n"

    # Pre-populate SQLite as if the poller had just ingested this comment.
    with state.connect() as conn:
        state.upsert_message(
            conn,
            MessageRow(
                comment_id=42,
                inbox_name=pgp_inbox.name,
                direction="in",
                author_login="evilsocket",
                created_at="2026-05-21T15:30:00Z",
                updated_at="2026-05-21T15:30:00Z",
                body_raw=comment_body,
                body_trimmed=comment_body,
                body_decrypted=None,
                subject="Re: pgptest",
                in_reply_to_id=None,
            ),
        )

    # No GitHub round trip — we're testing the decrypt path, not the poller.
    monkeypatch.setattr(service, "fetch", lambda inbox: 0)

    result = service.read_message(pgp_inbox, 42)
    assert "Incoming encrypted reply" in result["body"]
    # Cached decrypt should land in body_decrypted column too.
    with state.connect() as conn:
        cached = state.get_message(conn, 42)
    assert cached is not None
    assert cached.body_decrypted is not None
    assert "Incoming encrypted reply" in cached.body_decrypted


# ---------- robustness ----------------------------------------------------


def test_read_message_with_no_pgp_block_passes_through(pgp_inbox, monkeypatch):
    """If an incoming message has no PGP block, return body as-is (not crash)."""
    with state.connect() as conn:
        state.upsert_message(
            conn,
            MessageRow(
                comment_id=43,
                inbox_name=pgp_inbox.name,
                direction="in",
                author_login="evilsocket",
                created_at="2026-05-21T15:31:00Z",
                updated_at="2026-05-21T15:31:00Z",
                body_raw="plain text reply, the user forgot to encrypt",
                body_trimmed="plain text reply, the user forgot to encrypt",
                body_decrypted=None,
                subject="Re: pgptest",
                in_reply_to_id=None,
            ),
        )
    monkeypatch.setattr(service, "fetch", lambda inbox: 0)
    result = service.read_message(pgp_inbox, 43)
    assert "plain text reply" in result["body"]


def test_inbox_pubkey_is_embedded_in_issue_body(pgp_inbox, inbox_key):
    """The seed-issue body should contain the inbox's public key so the user
    can fetch it to encrypt their first reply."""
    from nobox import message as msg_mod
    body = msg_mod.build_inbox_body(
        user_login="evilsocket",
        name=pgp_inbox.name,
        pgp_pub_armored=str(inbox_key.pubkey),
        uid_validity=pgp_inbox.uid_validity,
    )
    assert "BEGIN PGP PUBLIC KEY BLOCK" in body
    # The inbox's fingerprint should match what's on disk.
    d = state.inbox_dir(pgp_inbox.name)
    saved_pub = (d / "pgp.pub.asc").read_text()
    assert "BEGIN PGP PUBLIC KEY BLOCK" in saved_pub
